### ISSUE TITLE
Support more smarter cd command such as zoxide, z 

### ISSUE THREAD

**Issue by shootingfly** [webxmsj/vscode-autojump#1]
This project is very useful and surpised. 👍

But I changed my smarter cd command from autojump to zoxide yesterday, and then found this project.
If this project can support more smarter cd command, such as zoxide or z, it will be more surprised.

zoxide is a smarter cd command, inspired by z and autojump.
https://github.com/ajeetdsouza/zoxide

**Comment by webxmsj** [comment]
I'll look at zoxide or z, or you can try pr

**Comment by webxmsj** [comment]
> This project is very useful and surpised. 👍
> 
> But I changed my smarter cd command from autojump to zoxide yesterday, and then found this project. If this project can support more smarter cd command, such as zoxide or z, it will be more surprised.
> 
> zoxide is a smarter cd command, inspired by z and autojump. https://github.com/ajeetdsouza/zoxide

v0.0.4 已添加对z的支持,详见readme.md

**Comment by webxmsj** [comment]
已支持
https://github.com/webxmsj/vscode-autojump/blob/main/CHANGELOG.md

**Comment by shootingfly** [comment]
@webxmsj Good Job 👍🏻
